code/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using code.Data;
using code.Models;
using code.Repository;

public class ClienteController : Controller
{
    private readonly IClienteRepository _clienteRepository;

    public ClienteController(IClienteRepository clienteRepository)
    {
        _clienteRepository = clienteRepository;
    }

    public IActionResult Index()
    {
        var clientes = _clienteRepository.GetAll().ToList();


        return View(clientes);
    }

    // GET: Cliente/Create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(ClienteModel cliente)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _clienteRepository.Post(cliente);
                TempData["MensagemSucesso"] = "Cliente cadastrado com sucesso";
                return RedirectToAction("Index");
            }

            return View(cliente);
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos cadastrar seu cliente. Detalhes: {e.Message}";
            return RedirectToAction("Index");
        }

    }


    public IActionResult Edit(int id)
    {
        ClienteModel cliente = _clienteRepository.GetById(id);

        return View(cliente);
    }

    [HttpPost]
    public IActionResult SaveEdit(ClienteModel cliente)    {       

        try
        {
            if (ModelState.IsValid)
            {
                _clienteRepository.Update(cliente);
                TempData["MensagemSucesso"] = "Cliente alterado com sucesso";
                return RedirectToAction("Index");
            }

            return View("Edit", cliente);
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos alterar seu cliente. Detalhes: {e.Message}";
            return RedirectToAction("Edit");
        }
    }

    public IActionResult ConfirmDelete(int id)
    {
        ClienteModel cliente = _clienteRepository.GetById(id);

        return View(cliente);
    }

    public IActionResult Delete(int id)
    {
        try
        {
            bool isClienteDeleted = _clienteRepository.Delete(id);

            if (isClienteDeleted)
            {
                TempData["MensagemSucesso"] = "Cliente deletado com sucesso!";                
            }
            else
            {
                TempData["MensagemErro"] = "Cliente não foi deletado!";
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos deletar seu contato. Detalhes: {e.Message}";
            return RedirectToAction("Index");
        }
    }
}

code/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using code.Data;
using code.Models;
using code.Repository;

public class ProdutoController : Controller
{
    private readonly IProdutoRepository _produtoRepository;

    public ProdutoController(IProdutoRepository produtoRepository)
    {
        _produtoRepository = produtoRepository;
    }

    public IActionResult Index()
    {
        var produtos = _produtoRepository.GetAll().ToList();

        return View(produtos);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(ProdutoModel produto)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _produtoRepository.Post(produto);
                TempData["MensagemSucesso"] = "Produto cadastrado com sucesso";
                return RedirectToAction("Index");
            }

            return View(produto);
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos cadastrar seu produto. Detalhes: {e.Message}";
            return RedirectToAction("Index");
        }

    }

    public IActionResult Edit(int id)
    {
        ProdutoModel produto = _produtoRepository.GetById(id);

        return View(produto);
    }

    [HttpPost]
    public IActionResult SaveEdit(ProdutoModel produto)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _produtoRepository.Update(produto);
                TempData["MensagemSucesso"] = "produto alterado com sucesso";
                return RedirectToAction("Index");
            }

            return View("Edit", produto);
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos alterar seu produto. Detalhes: {e.Message}";
            return RedirectToAction("Edit");
        }
    }

    public IActionResult ConfirmDelete(int id)
    {
        ProdutoModel produto = _produtoRepository.GetById(id);

        return View(produto);
    }

    public IActionResult Delete(int id)
    {
        try
        {
            bool isprodutoDeleted = _produtoRepository.Delete(id);

            if (isprodutoDeleted)
            {
                TempData["MensagemSucesso"] = "produto deletado com sucesso!";
            }
            else
            {
                TempData["MensagemErro"] = "produto não foi deletado!";
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos deletar este produto. Detalhes: {e.Message}";
            return RedirectToAction("Index");
        }
    }
}

code/Controllers/VendaController.cs
using Microsoft.AspNetCore.Mvc;
using code.Models;
using code.Repository;

public class VendaController : Controller
{
    private readonly IVendaRepository _vendaRepository;
    private readonly IClienteRepository _clienteRepository;
    private readonly IProdutoRepository _produtoRepository;

    public VendaController(IVendaRepository vendaRepository, IClienteRepository clienteRepository, IProdutoRepository produtoRepository)
    {
        _vendaRepository = vendaRepository;
        _clienteRepository = clienteRepository;
        _produtoRepository = produtoRepository;
    }

    public IActionResult Index(string searchString)
    {
        var vendas = _vendaRepository.GetAll();

        if (!string.IsNullOrEmpty(searchString))
        {
            vendas = vendas.Where(v => v.Cliente.NmCliente.Contains(searchString) || v.Produto.DscProduto.Contains(searchString)).ToList();
        }

        return View(vendas);
    }

    public IActionResult Create()
    {
        ViewBag.Clientes = _clienteRepository.GetAll();
        ViewBag.Produtos = _produtoRepository.GetAll();
        return View();
    }

    [HttpPost]
    public IActionResult Create(VendaModel venda)
    {
        try
        {                         
            _vendaRepository.Post(venda);
            TempData["MensagemSucesso"] = "Venda cadastrada com sucesso";
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos cadastrar sua venda. Detalhes: {e.Message}";
            return RedirectToAction("Index");
        }
    }

    public IActionResult Edit(int id)
    {
        VendaModel venda = _vendaRepository.GetById(id);
        ViewBag.Clientes = _clienteRepository.GetAll();
        ViewBag.Produtos = _produtoRepository.GetAll();
        return View(venda);
    }

    [HttpPost]
    public IActionResult SaveEdit(VendaModel venda)
    {
        try
        {               
            _vendaRepository.Update(venda);
            TempData["MensagemSucesso"] = "Venda alterada com sucesso";

            var objCliente = _clienteRepository.GetAll();
            var objProduto = _produtoRepository.GetAll();

            venda.Cliente = objCliente.FirstOrDefault(x => x.IdCliente != null & x.IdCliente == venda.IdCliente);
            venda.Produto = objProduto.FirstOrDefault(x => x.IdProduto != null & x.IdProduto == venda.IdProduto);

            ViewBag.Clientes = objCliente;
            ViewBag.Produtos = objProduto;
            View("Edit", venda);
            return RedirectToAction("Index");

            //return View("Edit", venda);
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos alterar sua venda. Detalhes: {e.Message}";
            return RedirectToAction("Edit");
        }
    }

    public IActionResult ConfirmDelete(int id)
    {
        VendaModel venda = _vendaRepository.GetById(id);
        return View(venda);
    }

    public IActionResult Delete(int id)
    {
        try
        {
            bool isVendaDeleted = _vendaRepository.Delete(id);

            if (isVendaDeleted)
            {
                TempData["MensagemSucesso"] = "Venda deletada com sucesso!";
            }
            else
            {
                TempData["MensagemErro"] = "Venda não foi deletada!";
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            TempData["MensagemErro"] = $"Não conseguimos deletar esta venda. Detalhes: {e.Message}";
            return RedirectToAction("Index");
        }
    }
}

code/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @* <script src="https://cdn.tailwindcss.com"></script> *@
    <title>@ViewData["Title"] - Teste Campos Dealer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/code.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.8/datatables.min.css" rel="stylesheet">    
</head>
<body class="">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Loja</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venda" asp-action="Index">Vendas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Teste Campos Dealer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.8/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>